src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\JoinColumn;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 * @Vich\Uploadable
 */
class User extends BaseUser
{

    /**
     * @var User[]
     * @ORM\ManyToMany(targetEntity="user")
     * @ORM\JoinTable(name="user_user", joinColumns={@JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@JoinColumn(name="follower_id", referencedColumnName="id")})
     */
    private $followers;

    /**
     * @var User[]
     * @ORM\ManyToMany(targetEntity="user",mappedBy="followers")
     */
    private $user_follow;

    /**
     * @var Image[]
     * @ORM\OneToMany(targetEntity="Image", mappedBy="user")
     */
    private $images;

    /**
     * @var Comment[]
     * @ORM\OneToMany(targetEntity="Comment",mappedBy="user")
     */
    private $comments;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->followers = new ArrayCollection();
        $this->user_follow = new ArrayCollection();
    }

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", nullable= true, unique= false)
     */
    private $avatar;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="avatar_file", fileNameProperty="avatar")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @var \DateTime
     * @ORM\Column(name="update_at",type="datetime",nullable=true)
     */
    private $updateAt;

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return User
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function __toString()
    {
        return $this->email ?: '';
    }

    /**
     * @param string $avatar
     * @return User
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;
        return $this;
    }

    /**
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * @param \DateTime $updateAt
     * @return User
     */
    public function setUpdateAt($updateAt)
    {
        $this->updateAt = $updateAt;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdateAt()
    {
        return $this->updateAt;
    }

    /**
     * @param Image[] $images
     * @return User
     */
    public function setImages($images)
    {
        $this->images = $images;
        return $this;
    }

    /**
     * @return Image[]
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * @param Comment[] $comments
     * @return User
     */
    public function setComments($comments)
    {
        $this->comments[] = $comments;
        return $this;
    }

    /**
     * @return Comment[]
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @return User[]
     */
    public function getFollowers()
    {
        return $this->followers;
    }

    /**
     * @param $follower User
     * @return User
     */
    public function addFollower($follower)
    {
        $this->followers[] = $follower;
        return $this;
    }

    /**
     * @param User $user
     * @return User
     */
    public function removeFollower($user)
    {
        $this->followers->removeElement($user);
        return $this;
    }

    /**
     * @param User[] $user_follow
     * @return User
     */
    public function setUserFollow($user_follow)
    {
        $this->user_follow[] = $user_follow;
        return $this;
    }

    /**
     * @return User[]
     */
    public function getUserFollow()
    {
        return $this->user_follow;
    }

    /**
     *
     */
    public function getUserFollowId()
    {
        $usersId[] = $this->getId();
        $users = $this->getUserFollow();
        foreach ($users as $value) {
            $usersId[] = $value->getId();
        }

        return $usersId;
    }
}

src/AppBundle/Controller/PagesControllerController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Comment;
use AppBundle\Entity\Image;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;

class PagesControllerController extends Controller
{
    /**
     * @Route("/")
     */
    public function indexAction()
    {
        if ($this->isGranted('ROLE_USER', $this->getUser())) {
            return $this->redirectToRoute('app_pagescontroller_tape');
        }
        return $this->redirectToRoute('fos_user_registration_register');
    }

    /**
     * @Route("/tape")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function tapeAction()
    {
        $image = new Image();
        $form = $this->createForm('AppBundle\Form\ImageType', $image);
        $comment = new Comment();
        $form_comment = $this->createForm('AppBundle\Form\CommentType', $comment);

        $usersId = $this->getUser()->getUserFollowId();

        $images = $this->getDoctrine()->getRepository('AppBundle:Image')->findBy(['user' => $usersId], ['id' => 'DESC']);

        return $this->render('@App/PagesController/index.html.twig', [
            'images' => $images,
            'form' => $form->createView(),
            'formComment' => $form_comment,
        ]);
    }

    /**
     * @Route("/tape/{id}/profile")
     * @param $id int
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function profileAction($id)
    {
        $user = $this->getDoctrine()->getRepository('AppBundle:User')->find($id);
        if ($user) {
            $form = $this->createFormBuilder($user)->add('imageFile', FileType::class)->add('Сохранить', SubmitType::class)->getForm();

            return $this->render('@App/PagesController/profile.html.twig', [
                'user' => $user,
                'form' => $form->createView(),
            ]);
        }
        return $this->redirectToRoute('app_pagescontroller_tape');
    }

    /**
     * @Route("/tape/{id}/followers")
     * @param $id int
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function followerListAction($id)
    {
        $user = $this->getDoctrine()->getRepository('AppBundle:User')->find($id);
        if ($user) {
            $users = $user->getFollowers();
            return $this->render('@App/PagesController/list.html.twig', [
                'users' => $users,
            ]);
        }
        return $this->redirectToRoute('app_pagescontroller_tape');
    }

    /**
     * @Route("/tape/{id}/user-follow")
     * @param $id int
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function userFollowListAction($id)
    {
        $user = $this->getDoctrine()->getRepository('AppBundle:User')->find($id);
        if ($user) {
            $users = $user->getUserFollow();
            return $this->render('@App/PagesController/list.html.twig', [
                'users' => $users,
            ]);
        }
        return $this->redirectToRoute('app_pagescontroller_tape');
    }

    /**
     * @Route("/tape/search")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function searchAction(Request $request)
    {
        $users = $this->getDoctrine()->getRepository('AppBundle:User')->findBy(['username' => $request->get('searchName')]);

        return $this->render('@App/PagesController/list.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * @Route("/tape/img/{id}/likers")
     * @param $id int
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function likersListAction($id)
    {
        $image = $this->getDoctrine()->getRepository('AppBundle:Image')->find($id);
        if ($image) {
            $likers = $image->getLikers();
            return $this->render('@App/PagesController/list.html.twig', [
                'users' => $likers
            ]);
        }
        return $this->redirectToRoute('app_pagescontroller_tape');

    }
}

src/AppBundle/Resources/views/PagesController/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container" style="margin-top: 110px">

        {{ form_start(form,{ 'action' : path('app_entity_newimage') }) }}
        <div class="form-group">
            {{ form_row(form.imageFile,{'attr':{'class': 'form-control-file'}}) }}
            <br>
            <input type="submit" value="Поделиться" style="display: inline-block">
        </div>
        {{ form_end(form) }} </div>

    {% for image in images %}
        {% set form2 = formComment.createView %}
        <div class="container" style="margin-top: 40px">
            <div>
                <p style="padding: 20px">
                    <img src="{% if vich_uploader_asset(image.user,'imageFile') %}{{ vich_uploader_asset(image.user,'imageFile') }}{% else %}{{ asset('img/profileDefault.png') }}{% endif %}" alt="Avatar" width="30px">
                    <a href="{{ path('app_pagescontroller_profile',{'id' : image.user.id}) }}"> {{ image.user.username }}</a>
                </p>
            </div>
            <div>
                <img src="{{ vich_uploader_asset(image , 'imageFile') }}" alt="img" width="100%">
            </div>
            <div>
                <p><a href="{{ path('app_entity_addlike',{'id' : image.id}) }}">Нравиться! </a>| <a
                            href="{{ path('app_pagescontroller_likerslist',{'id':image.id}) }}">{{ image.likers | length }}</a>
                </p>
            </div>
            <div style="margin-top: 20px">
                <div style="padding-top: 20px;padding-left: 20px;padding-right: 20px; border: darkgray solid 1px;">
                    {% for comment in image.comments %}
                        <p>
                            <a href="{{ path('app_pagescontroller_profile',{'id' : comment.user.id}) }}">{{ comment.user.username }}
                                : </a>{{ comment.text }}
                            <span
                                    style="float: right">{{ comment.time | date('H:i:s | d-m-y') }}</span></p>
                        <hr>
                    {% else %}
                        <p>Нет коментариев</p>
                    {% endfor %}
                </div>
                {{ form_start(form2,{'action': path('app_entity_addcomment',{'id' : image.id})}) }}
                <div class="form-group">
                    {{ form_row(form2.text,{'attr':{'class': 'form-control'}}) }}
                </div>
                {{ form_end(form2) }}
            </div>

        </div>
    {% else %}
        <div class="container"><h6>Нет фото для отображения. Подпишитесь на новых людей чтобы видеть их публикации</h6>
        </div>
    {% endfor %}

{% endblock %}

src/AppBundle/Resources/views/PagesController/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container" style="margin-top: 110px; padding: 30px">
        <table style="width: 100%">
            {% for user in users %}
                <tr>
                    <td>
                        <p>
                            <img width="30" height="30"
                                 src="{% if vich_uploader_asset(user,'imageFile') %}{{ vich_uploader_asset(user,'imageFile') }}{% else %}{{ asset('img/profileDefault.png') }}{% endif %}"
                                 alt="avatar">
                            <a href="{{ path('app_pagescontroller_profile',{'id' : user.id}) }}">{{ user.username }}</a>
                        <hr>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td><p>Нет Пользователей для отображения</p></td>
                </tr>
            {% endfor %}

        </table>

    </div>
{% endblock %}

src/AppBundle/Resources/views/PagesController/profile.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container" style="margin-top: 110px; padding: 30px">
        <table style="width: 100%">
            <tr>
                <td><p><span>Имя пользователя </span>{{ user.username }}</p></td>
                <td style="float: right"><p>
                        <a href="{{ path('app_pagescontroller_followerlist',{'id': user.id}) }}">Подписчиков</a> {{ user.followers | length }}
                    </p>
                </td>

            </tr>
            <tr>
                <td></td>
                <td style="float: right"><p><span>Публикаций</span> {{ user.images | length }}</p></td>
            </tr>
            <tr>
                <td>
                    <p><span>Email </span>{{ user.email }}</p>
                </td>
                <td style="float: right"><p><a href="{{ path('app_pagescontroller_userfollowlist',{'id': user.id}) }}">Подписки</a> {{ user.userFollow | length }}
                    </p></td>
            </tr>
            <tr>
                <td>
                    <img width="300px"
                         src="{% if vich_uploader_asset(user,'imageFile') %}{{ vich_uploader_asset(user,'imageFile') }}{% else %}{{ asset('img/profileDefault.png') }}{% endif %}"
                         alt="Avatar">
                    {% if user.id == app.user.id %}
                        <p id="avatarForm" style="margin-left: 80px;">
                            <a href="#" id="avatarChange">Изменить Аватар</a>
                        </p>
                    {% endif %}

                </td>
                <td style="float: right">
                    {% if app.user.id != user.id %}
                        {% if app.user in user.followers %}
                            <span>Вы подписаны </span><a
                                href="{{ path('app_entity_removefollower',{'id': user.id}) }}" class="btn btn-primary">Отписаться</a>
                        {% else %}
                            <a href="{{ path('app_entity_addfollower',{'id' : user.id}) }}" class="btn btn-primary">Подписаться</a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
    <div class="container" style="margin-top: 50px; padding: 30px">
        <h2>Публикации</h2>
        {% for image in user.images %}
            <div style="width: 230px;display: inline-block; padding: 5px">
                <img src="{{ vich_uploader_asset(image,'imageFile') }}" alt="img" width="100%">
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/jquery.js') }}"></script>
    <script type="text/javascript">
        $('#avatarChange').on('click', function (event) {
            event.preventDefault();
            let box = $('#avatarForm');
            box.html('');
            box.html(`{{ form(form,{'action' : path('app_entity_changeavatar',{'id' : user.id})}) }}`);
        });
    </script>
{% endblock %}